import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [todos, setTodos] = useState([])
  const titleRef = useRef()

  const onTitleChange = (event) => {
    const { value } = event.target;
    setTitle(value)
  }

  const handleSubmit = async (event) => {
    event.preventDefault();

    const { current: {  value: title }} = titleRef
    console.log({title})

    if(!title) return;

    const response = await fetch('/api/todos', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title, isCompleted: false})
    })
    
    const data = await response.json()

    console.log({data})

  }

  const renderTodos = () => {

    if(!todos) return <p>No todos</p>


    return <ul>
      {todos.map(todo => <li>{todo.title}</li>)}
    </ul>
  }

  useEffect(()=>{
    const getTodos = async () => {
      const response = await fetch('api/todos');
      const data = await response.json();
      console.log({data})
      setTodos(data.todos)
    }
    getTodos()

  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section>
          <h3>Create new todo</h3>
          <form onSubmit={handleSubmit}>
          <label>
            Title:
            <input type="text" ref={titleRef} />
          </label>
          <input type="submit" value="Submit" />
        </form>
        </section>

        <section>
          <h3>Todos List</h3>
          {renderTodos()}
        </section>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
